version: 0.2

env:
  variables:
    SOLUTION: .\Uoft Timetable Generator.sln
    PACKAGE_DIRECTORY: .\packages
    DOTNET_FRAMEWORK: 4.6.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
artifacts:
  files:
    - .\src\bin\Debug\*
